definitions:
  dto.ArticleCreateRequestDto:
    properties:
      body:
        minLength: 5
        type: string
      title:
        minLength: 5
        type: string
    required:
    - body
    - title
    type: object
  dto.ArticleDetailResponse:
    properties:
      body:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  dto.ArticleUpdateRequestDto:
    properties:
      body:
        minLength: 5
        type: string
      title:
        minLength: 5
        type: string
    required:
    - body
    - title
    type: object
  dto.AuthRequestDto:
    properties:
      password:
        minLength: 5
        type: string
      username:
        minLength: 1
        type: string
    required:
    - password
    - username
    type: object
  dto.PaginationResponseDtoExample:
    properties:
      is_has_next_page:
        example: true
        type: boolean
      limit:
        type: integer
      list:
        items: {}
        type: array
      total_entry:
        example: 100
        type: integer
      total_page:
        type: number
    type: object
  helper.Response:
    properties:
      data: {}
      message:
        example: ok
        type: string
      status:
        example: 200
        type: integer
    type: object
info:
  contact: {}
  title: SuperCMS documentation API
  version: "3.0"
paths:
  /articles:
    get:
      parameters:
      - example: 10
        in: query
        name: limit
        required: true
        type: integer
      - example: 1
        in: query
        name: page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.PaginationResponseDtoExample'
              type: object
      security:
      - BearerAuth: []
      summary: Get All Article
      tags:
      - Article
    post:
      parameters:
      - description: Article payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleCreateRequestDto'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: Create Article
      tags:
      - Article
  /articles/{id}:
    delete:
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: Delete Article
      tags:
      - Article
    get:
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ArticleDetailResponse'
              type: object
      security:
      - BearerAuth: []
      summary: Get Article Details
      tags:
      - Article
    patch:
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - description: Article payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleUpdateRequestDto'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: Update Article
      tags:
      - Article
  /auth/login:
    post:
      parameters:
      - description: Auth payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRequestDto'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Auth Login
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
